# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

alias vi=nvim
alias vim=nvim
alias gitter=gitter.bat
alias code=nvim

HISTSIZE=10

# prompt design
redColor="\[\033[01;31m\]"
greenColor="\[\033[01;32m\]"
yellowColor="\[\033[01;33m\]"
blueColor="\[\033[01;34m\]"
whiteColor="\[\033[01;37m\]"
date="\d"
PS1="${redColor}[${date}] ${greenColor}\u ${yellowColor}\w\n${blueColor}-> ${whiteColor}"
